version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: tg_bot_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Jsddqh3x
      POSTGRES_DB: myDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build: .
    container_name: tg_bot_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:Jsddqh3x@db:5432/myDB
    stdin_open: true 
    tty: true 

volumes:
  pgdata:
