"""Initial

Revision ID: 4977bf4400a2
Revises: bbb6fd9db4eb
Create Date: 2026-05-18 19:56:11.186710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4977bf4400a2'
down_revision: Union[str, Sequence[str], None] = 'bbb6fd9db4eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('report_count', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('banned', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banned')
    op.drop_column('users', 'report_count')
    # ### end Alembic commands ###
