"""Initial

Revision ID: a66f54ca3457
Revises: 6d06e5ebd5e1
Create Date: 2026-05-24 20:28:49.066245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66f54ca3457'
down_revision: Union[str, Sequence[str], None] = '6d06e5ebd5e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_admin = False")
    op.alter_column('users', 'is_admin', nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
